--------------------------------------------------------
-- This file is autogenerated by pioasm; do not edit! --
--------------------------------------------------------

pragma Style_Checks (Off);

with RP.PIO;

package Picowi.PIO_SPI_Code is
   pragma Preelaborate;

   ----------------
   -- Picowi_Pio --
   ----------------

   Picowi_Pio_Wrap_Target : constant := 0;
   Picowi_Pio_Wrap        : constant := 3;

   Offset_stall : constant := 0;
   Offset_writer : constant := 0;
   Offset_reader : constant := 4;
   Offset_slow_reader : constant := 15;

   Picowi_Pio_Program_Instructions : RP.PIO.Program := (
                    --  .wrap_target
         16#80a0#,  --   0: pull   block           side 0
         16#a042#,  --   1: nop                    side 0
         16#6001#,  --   2: out    pins, 1         side 0
         16#10e1#,  --   3: jmp    !osre, 1        side 1
                    --  .wrap
         16#80a0#,  --   4: pull   block           side 0
         16#6020#,  --   5: out    x, 32           side 0
         16#e047#,  --   6: set    y, 7            side 0
         16#b042#,  --   7: nop                    side 1
         16#b042#,  --   8: nop                    side 1
         16#b042#,  --   9: nop                    side 1
         16#4001#,  --  10: in     pins, 1         side 0
         16#0087#,  --  11: jmp    y--, 7          side 0
         16#8020#,  --  12: push   block           side 0
         16#0046#,  --  13: jmp    x--, 6          side 0
         16#0004#,  --  14: jmp    4               side 0
         16#80a0#,  --  15: pull   block           side 0
         16#6020#,  --  16: out    x, 32           side 0
         16#e047#,  --  17: set    y, 7            side 0
         16#a042#,  --  18: nop                    side 0
         16#4001#,  --  19: in     pins, 1         side 0
         16#b042#,  --  20: nop                    side 1
         16#1092#,  --  21: jmp    y--, 18         side 1
         16#8020#,  --  22: push   block           side 0
         16#0051#,  --  23: jmp    x--, 17         side 0
         16#000f#); --  24: jmp    15              side 0

end Picowi.PIO_SPI_Code;
