# SPDX-FileCopyrightText: 2026 Max Reznik <reznikmm@gmail.com>
#
# SPDX-License-Identifier: MIT

name = "blink"
description = "Blink WiFi LED demo"
version = "0.1.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "MIT"
website = ""
tags = []

executables = ["blink"]

[build-switches]
development.optimization = ["-O0"]
development.style_checks = ["-gnaty", "-gnaty-B"]
development.contracts = "Yes"
"*".debug_info = "Yes"

[[actions]]
type = "post-build"
command = ["arm-eabi-objcopy", "-Obinary", "blink", "blink.bin"]
directory = "bin"

[[depends-on]]
picowi = "*"
sdpcm = "*"
light_tasking_rp2350 = "*"

[configuration.values]
light_tasking_rp2350.Board = "rpi_pico2"
light_tasking_rp2350.Max_CPUs = 1
rp2040_hal.Device = "RP2350A"

[[pins]]
picowi = { path='../../picowi' }
sdpcm = { path='../..' }
